# Generated by Django 3.2.6 on 2021-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresosesion',
            name='vidas',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='progresosesion',
            name='preguntas_disponibles',
            field=models.CharField(default='1,2,3,4,5', max_length=255),
        ),
    ]
