# Generated by Django 3.2.6 on 2021-08-27 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210823_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_usuarios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 39, 30, 862181))),
            ],
        ),
        migrations.CreateModel(
            name='PartidasDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 39, 30, 862512))),
            ],
        ),
        migrations.AddField(
            model_name='progresosesion',
            name='primera_partida',
            field=models.BooleanField(default=True),
        ),
    ]
