# Generated by Django 3.2.6 on 2021-08-31 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210827_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresosesion',
            name='buffer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progresosesion',
            name='es_valido',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 23, 20, 43, 212467)),
        ),
        migrations.AlterField(
            model_name='partidasdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 23, 20, 43, 213035)),
        ),
    ]
