# Generated by Django 3.2.6 on 2021-08-31 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210831_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 23, 23, 46, 117845)),
        ),
        migrations.AlterField(
            model_name='partidasdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 23, 23, 46, 118113)),
        ),
        migrations.AlterField(
            model_name='progresosesion',
            name='buffer',
            field=models.IntegerField(default=0),
        ),
    ]
